# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I1xu11AJnBdLKYEsw3Q7CpsDiwlTtocF
"""

import requests
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/County Wise Population Density.xlsx')

df = df.drop(['Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11'],axis = 1)

df.info()

counties = list(df['FIPS CODE'].unique())

counties