# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I1xu11AJnBdLKYEsw3Q7CpsDiwlTtocF
"""

import requests
import pandas as pd

url = 'https://data.cdc.gov/api/views/8xkx-amqh/rows.csv?'
df = pd.read_csv(url)

df.info()

columns = df.columns

df.describe()

vaccines = ['Series_Complete_Pop_Pct', 'Series_Complete_Yes',
       'Series_Complete_12Plus', 'Series_Complete_12PlusPop_Pct',
       'Series_Complete_18Plus', 'Series_Complete_18PlusPop_Pct',
       'Series_Complete_65Plus', 'Series_Complete_65PlusPop_Pct',
       'Completeness_pct', 'Administered_Dose1_Recip',
       'Administered_Dose1_Pop_Pct', 'Administered_Dose1_Recip_12Plus',
       'Administered_Dose1_Recip_12PlusPop_Pct',
       'Administered_Dose1_Recip_18Plus',
       'Administered_Dose1_Recip_18PlusPop_Pct',
       'Administered_Dose1_Recip_65Plus',
       'Administered_Dose1_Recip_65PlusPop_Pct',
       'Series_Complete_Pop_Pct_SVI', 'Series_Complete_12PlusPop_Pct_SVI',
       'Series_Complete_18PlusPop_Pct_SVI',
       'Series_Complete_65PlusPop_Pct_SVI',
       'Series_Complete_Pop_Pct_UR_Equity',
       'Series_Complete_12PlusPop_Pct_UR_Equity',
       'Series_Complete_18PlusPop_Pct_UR_Equity',
       'Series_Complete_65PlusPop_Pct_UR_Equity']
vaccines1 = ['FIPS','Series_Complete_Pop_Pct', 'Series_Complete_Yes',
       'Series_Complete_12Plus', 'Series_Complete_12PlusPop_Pct',
       'Series_Complete_18Plus', 'Series_Complete_18PlusPop_Pct',
       'Series_Complete_65Plus', 'Series_Complete_65PlusPop_Pct',
       'Completeness_pct', 'Administered_Dose1_Recip',
       'Administered_Dose1_Pop_Pct', 'Administered_Dose1_Recip_12Plus',
       'Administered_Dose1_Recip_12PlusPop_Pct',
       'Administered_Dose1_Recip_18Plus',
       'Administered_Dose1_Recip_18PlusPop_Pct',
       'Administered_Dose1_Recip_65Plus',
       'Administered_Dose1_Recip_65PlusPop_Pct',
       'Series_Complete_Pop_Pct_SVI', 'Series_Complete_12PlusPop_Pct_SVI',
       'Series_Complete_18PlusPop_Pct_SVI',
       'Series_Complete_65PlusPop_Pct_SVI',
       'Series_Complete_Pop_Pct_UR_Equity',
       'Series_Complete_12PlusPop_Pct_UR_Equity',
       'Series_Complete_18PlusPop_Pct_UR_Equity',
       'Series_Complete_65PlusPop_Pct_UR_Equity']

df['Date'] = pd.to_datetime(df['Date'])
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df.dropna(subset = ['FIPS'],inplace = True)
df['FIPS'] = df['FIPS'] #= usdata['census_fips_code'].apply(lambda x: '{0:0>5}'.format(x) )

vaccinations2021 = pd.DataFrame(df.loc[df['year'] == 2021])

vaccinations2021 = vaccinations2021.drop(['Date'],axis=1)

vaccinations2021

county = list(vaccinations2021['FIPS'].unique())

columns = columns[1:]

for j in range(1,10):
  dfco = pd.DataFrame(columns = columns)
  for i in county:    
     data = pd.DataFrame(vaccinations2021.loc[(vaccinations2021['FIPS'] == i) & (vaccinations2021['month'] == j)])
     d = pd.DataFrame(vaccinations2021.loc[(vaccinations2021['FIPS'] == i) & (vaccinations2021['month'] == j)])
     d = d.drop((vaccines),axis=1)
     d = d.drop_duplicates(subset = 'FIPS')
     da =pd.DataFrame(data[vaccines].mean())
     da = da.transpose()
     da['FIPS'] = str(i)
     fd = pd.merge(d,da,on = 'FIPS')
     objs = [dfco,fd]
     dfco = pd.concat(objs,axis = 0)
     dfco.reset_index(drop = True,inplace = True)
     print(dfco)
  name = '/content/drive/MyDrive/Colab Notebooks/Vaccinations 2021 Month' + str(j) +'.csv'
  dfco.to_csv(name)

import requests
import pandas as pd

url = 'https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv'
df = pd.read_csv(url)

df.info()
columns = df.columns
usdata = df.loc[df['country_region'] == 'United States']
usdata['date'] = pd.to_datetime(usdata['date'])
usdata['year'] = usdata['date'].dt.year
usdata['month'] = usdata['date'].dt.month

mobility2021 = pd.DataFrame(usdata.loc[usdata['year'] == 2021])

mobility2021

county = list(usdata['census_fips_code'].unique())

dfco = pd.DataFrame(columns = columns)

for j in range(1,10):
  dfco = pd.DataFrame(columns = columns)
  for i in county:    
     data = pd.DataFrame(mobility2021.loc[(mobility2021['census_fips_code'] == i) & (mobility2021['month'] == j)])
     mobility = ['date','month','year','retail_and_recreation_percent_change_from_baseline','grocery_and_pharmacy_percent_change_from_baseline','parks_percent_change_from_baseline','transit_stations_percent_change_from_baseline','workplaces_percent_change_from_baseline','residential_percent_change_from_baseline']
     mobility1 = ['census_fips_code','month','retail_and_recreation_percent_change_from_baseline','grocery_and_pharmacy_percent_change_from_baseline','parks_percent_change_from_baseline','transit_stations_percent_change_from_baseline','workplaces_percent_change_from_baseline','residential_percent_change_from_baseline']
     d = pd.DataFrame(mobility2021.loc[(mobility2021['census_fips_code'] == i) & (mobility2021['month'] == j)])
     d = d.drop((mobility),axis=1)
     d = d.drop_duplicates(subset = 'census_fips_code')
     da =pd.DataFrame(data[mobility1].mean())
     da = da.transpose()
     fd = pd.merge(d,da,on = 'census_fips_code')
     objs = [dfco,fd]
     dfco = pd.concat(objs,axis = 0)
     dfco.reset_index(drop = True,inplace = True)
     print(dfco)
name = '/content/drive/MyDrive/Colab Notebooks/Mobility 2021 Month' + str(j) +'.xlsx'
dfco.to_excel(name)